---
title: "Modeling"
author: "Kim Costello"
format: html
editor: visual
---

```{r}
library(tidyverse)
library(tidymodels)
library(rpart)
```


```{r}
set.seed(123)
diabetes_split <- initial_split(diabetes_data, prop = .70)
diabetes_train <- training(diabetes_split)
diabetes_test <- testing(diabetes_split)
diabetes_5fold <- vfold_cv(diabetes_train, 5)
```

#### Classification Tree Model

Create Recipe
```{r}
tree_recipe <- recipe(diabetes_binary ~ ., data = diabetes_train) |>
  update_role(age, new_role = "ID") |>
  step_rm(gen_hlth, ment_hlth, any_healthcare) |>
  step_dummy(high_bp, high_chol, smoker, stroke, phys_activity,
             heart_diseaseor_attack, hvy_alcohol_consump, sex) |>
  step_normalize(bmi)

tree_recipe
```

Define model and engine. 
```{r}
tree_model <- decision_tree(tree_depth = tune(),
                            min_n = 20,
                            cost_complexity = tune()) |>
  set_engine("rpart") |>
  set_mode("classification")
```

Create workflow.
```{r}
tree_workflow <- workflow() |>
  add_recipe(tree_recipe) |>
  add_model(tree_model)
```

Fit workflow to CV folds. 
```{r}
class_wkf_folds <- tree_workflow |>
  tune_grid(resamples = diabetes_5fold,
            metrics = metric_set(mn_log_loss))

class_wkf_folds |>
  collect_metrics() |>
  arrange(mean)
```

Grab the best model's tuning parameter values. 
```{r}
best_class_tree <- select_best(class_wkf_folds, metric = "mn_log_loss")
best_class_tree
```

Finalize workflow and fit to the entire training data. 
```{r}
tree_final_wkf <- tree_workflow |>
  finalize_workflow(best_class_tree)
```

```{r}
final_tree_fit <- tree_final_wkf |>
  last_fit(diabetes_split)

```

#### Random Forest

